---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-php-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: pujamanish/php-app
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: my-php-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 90
      targetPort: 8081
  type: LoadBalancer
