apiVersion: v1
kind: Pod
metadata:
  name: index-pod
spec:
  containers:
    - name:  php-container
      image: php-app
      ports:
        - containerPort: 80
--
apiVersion: v1
kind: Service
metadata:
  name: index-service
spec:
  type: Nodeport
  ports:
      port: 80
  selector:
    name: index-pod
