---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-php-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: pujamanish/php-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-php-service
spec:
  selector:
    app: my-app
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
