apiVersion: v1
kind: Pod
metadata:
  name: index-pod
  labels:
     app: myapp
spec:
  containers:
    - name:  php-container
      image: pujaamanish/php-app
      ports:
        - containerPort: 80
--
apiVersion: v1
kind: Service
metadata:
  name: index-service
spec:
  type: Nodeport
  ports:
      port: 8080
      targetPort: 80
  selector:
    app: myapp
